[project]
name = "house-finder-sslv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Richard Rusevich", email = "nonamemailnum1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
house-finder-sslv = "house_finder_sslv.bot:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
